export const personalInfo = {
  name: "Md Abdullah Hossien Molla",
  displayName: "Abdullah Hossien",
  handle: "itzabd",
  title: "AI/ML Researcher & Full-Stack Developer",
  degree: "BSc Computer Science, Independent University, Bangladesh",
  taglines: [
    "Building Intelligent Systems",
    "ML for Healthcare Research",
    "Full-Stack Development",
    "Published AI Researcher",
    "Teaching & Mentoring",
  ],
  bio: "Final-year Computer Science student at Independent University, Bangladesh with a CGPA of 3.66. Research Assistant and Teaching Assistant with published papers at HCII 2026 (Springer) and IEEE. Building AI-powered platforms in healthcare, neurotechnology, and civic tech — bridging research and real-world impact.",
  location: "Dhaka, Bangladesh",
  email: "abdullahhossien0@gmail.com",
  phone: "+880-1628658775",
  github: "https://github.com/itzabd",
  linkedin: "https://www.linkedin.com/in/abdullah-hossien-12349b225/",
  portfolio: "https://itzabd.github.io",
  availability: "Open to Opportunities",
  resumeUrl: "#",
};

export const skills = [
  {
    category: "Languages",
    icon: "Code2",
    color: "from-blue-500 to-cyan-400",
    items: [
      { name: "Python", level: 90 },
      { name: "C/C++", level: 72 },
      { name: "Java", level: 78 },
      { name: "JavaScript", level: 85 },
      { name: "HTML/CSS", level: 88 },
    ],
  },
  {
    category: "ML & Data Science",
    icon: "Brain",
    color: "from-purple-500 to-pink-400",
    items: [
      { name: "Scikit-learn", level: 88 },
      { name: "PyTorch", level: 75 },
      { name: "Pandas / NumPy", level: 90 },
      { name: "Matplotlib / Seaborn", level: 85 },
      { name: "XGBoost", level: 80 },
      { name: "OpenCV", level: 72 },
    ],
  },
  {
    category: "Web Development",
    icon: "Layout",
    color: "from-cyan-500 to-blue-400",
    items: [
      { name: "Flask", level: 85 },
      { name: "React", level: 80 },
      { name: "Bootstrap", level: 88 },
      { name: "REST APIs", level: 85 },
      { name: "Express.js", level: 75 },
    ],
  },
  {
    category: "Database & Backend",
    icon: "Database",
    color: "from-green-500 to-emerald-400",
    items: [
      { name: "Supabase", level: 85 },
      { name: "PostgreSQL", level: 82 },
      { name: "SQL", level: 85 },
      { name: "Docker", level: 72 },
      { name: "Render", level: 78 },
    ],
  },
  {
    category: "Tools & Platforms",
    icon: "Wrench",
    color: "from-orange-500 to-amber-400",
    items: [
      { name: "Git / GitHub", level: 90 },
      { name: "Jupyter / Colab", level: 92 },
      { name: "VS Code", level: 90 },
      { name: "PyCharm", level: 85 },
      { name: "IntelliJ", level: 78 },
    ],
  },
  {
    category: "Design & Docs",
    icon: "Sparkles",
    color: "from-rose-500 to-red-400",
    items: [
      { name: "Overleaf (LaTeX)", level: 80 },
      { name: "Draw.io", level: 78 },
      { name: "Canva", level: 75 },
      { name: "Joblib", level: 72 },
    ],
  },
];

export const projects = [
  {
    id: "glohealth",
    title: "GloHealth AI",
    subtitle: "AI-Powered Health Symptom Reporting System",
    description:
      "Full-stack AI healthcare platform for disease prediction, geospatial disease analysis, and appointment management with explainable ML insights powered by XGBoost and Scikit-learn.",
    tech: ["Python", "Flask", "Scikit-learn", "XGBoost", "Supabase", "PostgreSQL", "Bootstrap"],
    github: "https://github.com/itzabd/GloHealth_Ai",
    live: null,
    featured: true,
    category: "Healthcare",
    gradient: "from-green-600/20 to-blue-600/20",
    border: "border-green-500/30",
    badge: "Featured",
  },
  {
    id: "mindwaveweb",
    title: "MindWaveWeb",
    subtitle: "LLM-Powered EEG Classification App",
    description:
      "AI-powered EEG analysis platform for cognitive pattern classification using machine learning and LLM-assisted insights (TinyLlama), with interactive web dashboards and Docker deployment.",
    tech: ["Python", "Flask", "Scikit-learn", "PyTorch", "TinyLlama", "Supabase", "Docker"],
    github: "https://github.com/itzabd/MindWaveWeb",
    live: null,
    featured: true,
    category: "AI/ML",
    gradient: "from-purple-600/20 to-cyan-600/20",
    border: "border-purple-500/30",
    badge: "Featured",
  },
  {
    id: "deshcare",
    title: "DeshCare Vaccine",
    subtitle: "Vaccination Management System",
    description:
      "Role-based platform (admin, operator, patient) to streamline vaccine registration and scheduling. Built with Flask, Supabase, and PostgreSQL for end-to-end vaccination workflow management.",
    tech: ["Python", "Flask", "Supabase", "PostgreSQL", "HTML/CSS", "JavaScript"],
    github: "https://github.com/itzabd/DeshCare-Vaccine-Vaccination-Management-System_Dbms_project",
    live: null,
    featured: true,
    category: "Healthcare",
    gradient: "from-blue-600/20 to-indigo-600/20",
    border: "border-blue-500/30",
    badge: "Featured",
  },
  {
    id: "streetvendor",
    title: "StreetVendor",
    subtitle: "Digital Vendor Management Platform",
    description:
      "Full-stack digital platform for street vendor registration, location management, QR-based identification, and document generation using Leaflet maps and REST APIs.",
    tech: ["React", "Express.js", "Supabase", "Leaflet", "JavaScript", "REST API"],
    github: "https://github.com/itzabd/StreetVendor",
    live: null,
    featured: true,
    category: "Web App",
    gradient: "from-orange-600/20 to-rose-600/20",
    border: "border-orange-500/30",
    badge: "Featured",
  },
  {
    id: "foodcourt",
    title: "Food Court Management",
    subtitle: "OOP-Driven Restaurant Management System",
    description:
      "Full-featured food court management system built with object-oriented principles in Java. Features order management, dynamic menu handling, and integrated payment processing.",
    tech: ["Java", "OOP", "Design Patterns", "System Architecture"],
    github: "https://github.com/itzabd/Food-Court-Management-System-oop-project-Group59-",
    live: null,
    featured: false,
    category: "Software Engineering",
    gradient: "from-yellow-600/20 to-orange-600/20",
    border: "border-yellow-500/30",
    badge: null,
  },
  {
    id: "weather",
    title: "Country & Weather API",
    subtitle: "Real-Time Data Integration Application",
    description:
      "Interactive web application combining live country and weather data APIs with a responsive Bootstrap UI, demonstrating REST API integration and asynchronous JavaScript.",
    tech: ["JavaScript", "Bootstrap", "CSS", "HTML", "REST APIs"],
    github: "https://github.com/itzabd/Country-and-Weather-Api-Project",
    live: null,
    featured: false,
    category: "Web App",
    gradient: "from-cyan-600/20 to-teal-600/20",
    border: "border-cyan-500/30",
    badge: null,
  },
  {
    id: "ar-history",
    title: "AR BD History",
    subtitle: "Augmented Reality Educational Platform",
    description:
      "Immersive AR application bringing Bangladeshi historical events to life through interactive visualization — making history engaging through cutting-edge educational technology.",
    tech: ["AR", "Educational Technology", "Interactive Learning"],
    github: "https://github.com/itzabd/Augmented_Reality_BD-History",
    live: null,
    featured: false,
    category: "EdTech",
    gradient: "from-violet-600/20 to-purple-600/20",
    border: "border-violet-500/30",
    badge: null,
  },
];

export const publications = [
  {
    title: "Liver Data Governance Challenges for Mobile App-Based Liver Care in Bangladesh",
    venue: "HCII 2026, Springer LNCS 16747",
    doi: "10.1007/978-3-032-30549-7_7",
    doiUrl: "https://doi.org/10.1007/978-3-032-30549-7_7",
    year: "2026",
    status: "Published",
    statusColor: "text-emerald-300 bg-emerald-500/20 border-emerald-500/30",
    icon: "BookOpen",
    tags: ["Healthcare AI", "Mobile Health", "Data Governance"],
  },
  {
    title: "Safety-Enhanced ML for Fetal Health Classification Using Cardiotocography Data",
    venue: "ICMLAS 2026, IEEE",
    doi: "10.1109/ICMLAS67792.2026.11483766",
    doiUrl: "https://doi.org/10.1109/ICMLAS67792.2026.11483766",
    year: "2026",
    status: "Published",
    statusColor: "text-blue-300 bg-blue-500/20 border-blue-500/30",
    icon: "HeartPulse",
    tags: ["ML", "Fetal Health", "Cardiotocography", "Safety AI"],
  },
  {
    title: "Braille for All: A $70 AI-Powered Braille Tutoring Robot",
    venue: "CCE 2026",
    doi: null,
    doiUrl: null,
    year: "2026",
    status: "Under Review (Phase-1 Accepted)",
    statusColor: "text-yellow-300 bg-yellow-500/20 border-yellow-500/30",
    icon: "Cpu",
    tags: ["Robotics", "Assistive Tech", "AI Education", "Braille"],
  },
];

export const experience = [
  {
    role: "Research Assistant",
    company: "Independent University, Bangladesh",
    period: "Dec 2025 – May 2026",
    type: "On-Campus",
    icon: "Brain",
    highlights: [
      "Supported faculty-led research on ML applications in healthcare data classification",
      "Conducted literature review, data preprocessing, and experiment design for ongoing publications",
    ],
  },
  {
    role: "Teaching Assistant",
    company: "Dept. of Computer Science & Engineering, IUB",
    period: "Nov 2024 – Jan 2026",
    type: "On-Campus",
    icon: "GraduationCap",
    highlights: [
      "Assisted faculty with course delivery, grading, and student evaluation for 100+ students per term",
      "Strengthened student understanding of foundational CS courses through office hours and review sessions",
    ],
  },
  {
    role: "Event Coordinator",
    company: "IUB Chess Club",
    period: "Feb 2024 – 2025",
    type: "On-Campus",
    icon: "Trophy",
    highlights: [
      "Coordinated logistics and registrations for the July Memorial FIDE Chess Championship (IUB)",
      "Ensured compliance with FIDE regulations for international-standard chess events",
    ],
  },
];

export const education = [
  {
    degree: "Bachelor of Science in Computer Science",
    institution: "Independent University, Bangladesh",
    period: "2022 – Expected Dec 2026",
    cgpa: "3.66",
    status: "In Progress",
    highlights: [
      "Database Management Systems",
      "Object-Oriented Programming",
      "System Design & Analysis",
      "Compiler Design",
      "Artificial Intelligence",
      "Web Development",
    ],
  },
  {
    degree: "Higher Secondary Certificate (HSC)",
    institution: "Govt. Science College, Tejgaon",
    period: "2020",
    cgpa: "GPA 5.00",
    status: "Completed",
    highlights: [],
  },
  {
    degree: "Secondary School Certificate (SSC)",
    institution: "Ideal School and College, Dhaka",
    period: "2018",
    cgpa: "GPA 5.00",
    status: "Completed",
    highlights: [],
  },
];

export const researchAreas = [
  {
    year: "2025–2026",
    title: "ML for Healthcare Classification",
    description:
      "Research Assistantship focused on applying machine learning to healthcare data — including fetal health classification using Cardiotocography data and liver care data governance, resulting in two published papers.",
    tags: ["ML", "Healthcare", "Cardiotocography", "Liver Care"],
    icon: "HeartPulse",
    color: "text-rose-400",
  },
  {
    year: "2025–2026",
    title: "AI-Powered Braille Tutoring Robot",
    description:
      "Designed a low-cost ($70) AI-powered Braille tutoring robot for accessibility education, currently under review at CCE 2026 (Phase-1 Accepted).",
    tags: ["Robotics", "Assistive Tech", "AI", "Education"],
    icon: "Cpu",
    color: "text-cyan-400",
  },
  {
    year: "2024–2025",
    title: "EEG-LLM Fusion Research",
    description:
      "Pioneered the application of Large Language Models (TinyLlama) for EEG brainwave classification. MindWaveWeb demonstrates real-time cognitive pattern analysis, bridging neuroscience and generative AI.",
    tags: ["EEG", "LLM", "Neurotechnology", "Signal Processing"],
    icon: "Brain",
    color: "text-purple-400",
  },
  {
    year: "2024",
    title: "Healthcare AI Systems",
    description:
      "Designed and implemented AI-integrated healthcare platforms including GloHealth AI — focusing on explainable ML, geospatial disease analysis, and scalable architecture for real-world clinical applications.",
    tags: ["Healthcare", "Explainable AI", "XGBoost", "Geospatial"],
    icon: "Glasses",
    color: "text-green-400",
  },
];

export const achievements = [
  { value: "2", label: "Published Papers", icon: "BookOpen", color: "text-blue-400" },
  { value: "3.66", label: "CGPA", icon: "GraduationCap", color: "text-green-400" },
  { value: "4+", label: "Featured Projects", icon: "FolderGit2", color: "text-purple-400" },
  { value: "FIDE", label: "Chess Rating", icon: "Trophy", color: "text-yellow-400" },
  { value: "100+", label: "Students Taught", icon: "Layers", color: "text-cyan-400" },
  { value: "Merit", label: "Dean's List", icon: "Sparkles", color: "text-rose-400" },
];
